sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    access-key-id: LTAI5t9BpBZZUYhPyjWaRAzh
    access-key-secret: ytC4bZ0lYtVwNDSG9TzLyWIrb6xtfW
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-itcast-12138
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxf6d3b9f931bfb68d
    secret: ab12057e415660195b4fc08d26f7aa8b
